name             "zg-base"
maintainer       "ZehnerGroup"
maintainer_email "aduro@zehnergroup.com"
license          "All rights reserved"
description      "Installs/Configures a generic base server profile"
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          "0.1.0"

depends "htop"
depends "apt"
depends "python"
depends "mysql"
depends "application"
depends "application_python", "~> 1.0.8"
depends "git"
depends "supervisor"
depends "php"
depends "firewall"
depends "hostsfile"
depends "database"
